### ISSUE TITLE
TypeError: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by paulbjensen** [anephenix/satellite#4]
```
/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:103
    var proxyReq = (options.target.protocol === 'https:' ? https : http).reque
                                  ^
TypeError: Cannot read property 'protocol' of undefined
    at Array.stream [as 3] (/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:103:35)
    at ProxyServer.<anonymous> (/node_modules/http-proxy/lib/http-proxy/index.js:83:21)
    at Server.closure (/node_modules/http-proxy/lib/http-proxy/index.js:125:43)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)
```

**Comment by paulbjensen** [comment]
Closing as this is an old issue.
